-- Workforce app — initial schema.
-- Draft, modeled on a prior HTML prototype's domain shape. Expect fields and
-- workflows to change as each feature is actually built — this is a
-- foundation, not a locked-in spec.
--
-- ONE-TIME MANUAL STEP before anything else works:
--   Store an encryption key for sensitive staff data (bank details, TFN,
--   super) in Supabase Vault — generated by you, never committed to this
--   repo. (A custom Postgres GUC via `alter database ... set` was the
--   original plan, but Supabase's hosted SQL editor doesn't grant that
--   permission — Vault is their supported equivalent.)
--
--     select vault.create_secret('a-long-random-string', 'app_encryption_key');
--
--   Run that once in the Supabase SQL editor before running this migration.

create extension if not exists pgcrypto;

-- =========================================================================
-- People
-- =========================================================================

-- Every person (admin or staff) gets a profile row with its own id.
-- auth_user_id is only set for people who log into the web dashboard via
-- Supabase Auth (superadmin/admin/operations). Staff sign in on mobile via
-- PIN (see verify_staff_pin below), not Supabase Auth, so their
-- auth_user_id stays null.
create table profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users (id) on delete set null,
  full_name text not null,
  email text, -- contact/reference email; independent of auth_user_id's login email
  role text not null default 'staff'
    check (role in ('superadmin', 'admin', 'operations', 'staff')),
  position text,
  start_date date,
  pin_hash text, -- bcrypt hash (pgcrypto crypt/gen_salt('bf'))
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- 1:1 sensitive/compliance data, split out so it can be locked down harder
-- than the rest of a staff profile. Bank/tax/super numbers are encrypted at
-- rest (see encrypt_sensitive/decrypt_sensitive below) — never stored or
-- queried as plain text.
create table staff_sensitive (
  profile_id uuid primary key references profiles (id) on delete cascade,
  address jsonb,
  bank_account_name text,
  bank_bsb_encrypted bytea,
  bank_account_number_encrypted bytea,
  tax_type text check (tax_type in ('TFN', 'ABN')),
  tfn_encrypted bytea,
  abn text,
  super_fund_name text,
  super_member_number_encrypted bytea,
  visa_status text,
  visa_expiry date,
  forklift_licence_expiry date,
  lo_licence_expiry date,
  updated_at timestamptz not null default now()
);

-- security definer: only these functions can read the vault secret;
-- callers (even admins) only ever see the encrypt/decrypt result, never the
-- key itself. vault.decrypted_secrets is restricted to the postgres role,
-- which is what these functions run as.
create or replace function encrypt_sensitive(plain text) returns bytea
language sql stable security definer as $$
  select pgp_sym_encrypt(
    plain,
    (select decrypted_secret from vault.decrypted_secrets where name = 'app_encryption_key')
  );
$$;

create or replace function decrypt_sensitive(cipher bytea) returns text
language sql stable security definer as $$
  select pgp_sym_decrypt(
    cipher,
    (select decrypted_secret from vault.decrypted_secrets where name = 'app_encryption_key')
  );
$$;

revoke all on function encrypt_sensitive(text) from public;
revoke all on function decrypt_sensitive(bytea) from public;
grant execute on function encrypt_sensitive(text) to authenticated;
grant execute on function decrypt_sensitive(bytea) to authenticated;

-- =========================================================================
-- Customers (client sites) & rate cards
-- =========================================================================

create table customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  address jsonb,
  operating_hours text,
  created_at timestamptz not null default now()
);

create table rate_cards (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references customers (id) on delete cascade,
  work_type text not null check (work_type in ('hourly', 'container', 'rework')),
  position_or_type text not null,
  size text,
  charge_rate numeric(10, 2),
  pay_rate numeric(10, 2)
);

-- =========================================================================
-- Roster
-- =========================================================================

create table shifts (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references customers (id) on delete cascade,
  date date not null,
  start_time time not null,
  shift_type text not null check (shift_type in ('hourly', 'container', 'rework')),
  status text not null default 'draft' check (status in ('draft', 'confirmed')),
  created_at timestamptz not null default now()
);

create table shift_assignments (
  id uuid primary key default gen_random_uuid(),
  shift_id uuid not null references shifts (id) on delete cascade,
  staff_id uuid not null references profiles (id) on delete cascade,
  role text not null
);

-- =========================================================================
-- Time & attendance
-- =========================================================================

create table sign_ons (
  id uuid primary key default gen_random_uuid(),
  shift_id uuid not null references shifts (id) on delete cascade,
  staff_id uuid not null references profiles (id) on delete cascade,
  sign_on_time timestamptz not null default now(),
  sign_off_time timestamptz
);

create table breaks (
  id uuid primary key default gen_random_uuid(),
  sign_on_id uuid not null references sign_ons (id) on delete cascade,
  start_time timestamptz not null,
  end_time timestamptz
);

-- =========================================================================
-- Container / rework jobs
-- =========================================================================

create table jobs (
  id uuid primary key default gen_random_uuid(),
  shift_id uuid not null references shifts (id) on delete cascade,
  job_type text not null check (job_type in ('container', 'rework')),
  type text not null,
  size text,
  quantity numeric,
  status text not null default 'pending'
    check (status in ('pending', 'started', 'paused', 'finalised')),
  created_at timestamptz not null default now()
);

create table job_crew (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references jobs (id) on delete cascade,
  staff_id uuid not null references profiles (id) on delete cascade,
  participation_pct numeric(5, 2)
);

create table ncr_reports (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references jobs (id) on delete cascade,
  issues text[] not null default '{}',
  photo_urls text[] not null default '{}',
  created_at timestamptz not null default now()
);

-- =========================================================================
-- Leave
-- =========================================================================

create table leave_requests (
  id uuid primary key default gen_random_uuid(),
  staff_id uuid not null references profiles (id) on delete cascade,
  type text not null,
  start_date date not null,
  end_date date not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'declined')),
  created_at timestamptz not null default now()
);

-- =========================================================================
-- Safety
-- =========================================================================

create table hazard_reports (
  id uuid primary key default gen_random_uuid(),
  staff_id uuid not null references profiles (id) on delete cascade,
  customer_id uuid references customers (id),
  category text,
  description text not null,
  severity text,
  status text not null default 'open' check (status in ('open', 'in_review', 'resolved')),
  created_at timestamptz not null default now()
);

-- Full WHS-style field set (injured person details, investigation factors,
-- prevention actions, sign-off) is deferred until this feature is actually
-- built — kept minimal here on purpose.
create table incident_reports (
  id uuid primary key default gen_random_uuid(),
  report_no text unique not null,
  staff_id uuid not null references profiles (id) on delete cascade,
  customer_id uuid references customers (id),
  description text not null,
  status text not null default 'open' check (status in ('open', 'in_review', 'resolved')),
  created_at timestamptz not null default now()
);

-- =========================================================================
-- Audit log
-- =========================================================================

create table audit_log (
  id bigint generated always as identity primary key,
  actor_profile_id uuid references profiles (id),
  table_name text not null,
  row_id uuid,
  action text not null check (action in ('select', 'insert', 'update', 'delete')),
  occurred_at timestamptz not null default now()
);

create or replace function log_audit(p_table_name text, p_row_id uuid, p_action text)
returns void
language plpgsql security definer as $$
begin
  insert into audit_log (actor_profile_id, table_name, row_id, action)
  values (
    (select id from profiles where auth_user_id = auth.uid()),
    p_table_name,
    p_row_id,
    p_action
  );
end;
$$;

create or replace function audit_staff_sensitive() returns trigger
language plpgsql security definer as $$
begin
  perform log_audit('staff_sensitive', coalesce(new.profile_id, old.profile_id), lower(tg_op));
  return coalesce(new, old);
end;
$$;

create trigger staff_sensitive_audit
  after insert or update or delete on staff_sensitive
  for each row execute function audit_staff_sensitive();

-- Note: this only covers writes. Auditing reads of staff_sensitive requires
-- either the pgaudit extension (may not be available on all Supabase plans)
-- or logging explicitly from the API route that serves this data — revisit
-- when the staff-details feature is actually built.

-- =========================================================================
-- Row Level Security — default deny, explicit grants only
-- =========================================================================

alter table profiles enable row level security;
alter table staff_sensitive enable row level security;
alter table customers enable row level security;
alter table rate_cards enable row level security;
alter table shifts enable row level security;
alter table shift_assignments enable row level security;
alter table sign_ons enable row level security;
alter table breaks enable row level security;
alter table jobs enable row level security;
alter table job_crew enable row level security;
alter table ncr_reports enable row level security;
alter table leave_requests enable row level security;
alter table hazard_reports enable row level security;
alter table incident_reports enable row level security;
alter table audit_log enable row level security;

-- Helper functions used across policies below. security definer is
-- deliberate here (corrected from an earlier security-invoker version):
-- these functions query `profiles` internally, and if that query were
-- itself subject to profiles' own RLS, evaluating profiles_admin_select
-- for someone else's row would call is_admin_or_ops() again, which runs
-- the same self-referential query again — expensive recursive evaluation
-- the moment any query selects more than just the caller's own profile
-- row. Bypassing RLS here is safe: the check itself ("is this auth.uid()
-- an active admin/ops/superadmin") doesn't depend on RLS.
create or replace function is_admin_or_ops() returns boolean
language sql stable security definer as $$
  select exists (
    select 1 from profiles
    where auth_user_id = auth.uid() and role in ('superadmin', 'admin', 'operations') and active
  );
$$;

create or replace function is_admin() returns boolean
language sql stable security definer as $$
  select exists (
    select 1 from profiles
    where auth_user_id = auth.uid() and role in ('superadmin', 'admin') and active
  );
$$;

create or replace function is_superadmin() returns boolean
language sql stable security definer as $$
  select exists (
    select 1 from profiles
    where auth_user_id = auth.uid() and role = 'superadmin' and active
  );
$$;

-- profiles: anyone can see their own row; admin/operations can see everyone.
-- Writes limited to admin/operations for now — role-escalation safeguards
-- (e.g. only superadmin can grant admin) are a future admin-management
-- feature, not enforced at this layer yet.
create policy profiles_self_select on profiles for select
  using (auth_user_id = auth.uid());
create policy profiles_admin_select on profiles for select
  using (is_admin_or_ops());
create policy profiles_admin_write on profiles for all
  using (is_admin_or_ops()) with check (is_admin_or_ops());

-- staff_sensitive: admin/superadmin only — operations does not get this.
create policy staff_sensitive_admin on staff_sensitive for all
  using (is_admin()) with check (is_admin());

-- Operational tables: admin/operations full access. Staff-side access
-- (mobile) is deliberately NOT via RLS — staff never hold a Supabase Auth
-- session in this design, so their reads/writes go through SECURITY DEFINER
-- RPC functions (like verify_staff_pin) that check identity explicitly.
-- Those RPCs are future work; only the PIN-verification one exists so far.
create policy customers_admin on customers for all
  using (is_admin_or_ops()) with check (is_admin_or_ops());
create policy rate_cards_admin on rate_cards for all
  using (is_admin_or_ops()) with check (is_admin_or_ops());
create policy shifts_admin on shifts for all
  using (is_admin_or_ops()) with check (is_admin_or_ops());
create policy shift_assignments_admin on shift_assignments for all
  using (is_admin_or_ops()) with check (is_admin_or_ops());
create policy sign_ons_admin on sign_ons for all
  using (is_admin_or_ops()) with check (is_admin_or_ops());
create policy breaks_admin on breaks for all
  using (is_admin_or_ops()) with check (is_admin_or_ops());
create policy jobs_admin on jobs for all
  using (is_admin_or_ops()) with check (is_admin_or_ops());
create policy job_crew_admin on job_crew for all
  using (is_admin_or_ops()) with check (is_admin_or_ops());
create policy ncr_reports_admin on ncr_reports for all
  using (is_admin_or_ops()) with check (is_admin_or_ops());
create policy leave_requests_admin on leave_requests for all
  using (is_admin_or_ops()) with check (is_admin_or_ops());
create policy hazard_reports_admin on hazard_reports for all
  using (is_admin_or_ops()) with check (is_admin_or_ops());
create policy incident_reports_admin on incident_reports for all
  using (is_admin_or_ops()) with check (is_admin_or_ops());

-- audit_log: superadmin can read; nothing can write directly (log_audit()
-- is SECURITY DEFINER and writes on the caller's behalf).
create policy audit_log_superadmin_select on audit_log for select
  using (is_superadmin());

-- =========================================================================
-- Staff PIN sign-in (mobile)
-- =========================================================================

-- Scans active profiles computing crypt() per row — there's no way to index
-- a bcrypt hash for direct lookup. Fine at hundreds-of-staff scale; revisit
-- if the list grows much larger.
--
-- Matches any role, not just 'staff': an admin/operations person can also
-- carry a PIN and use the mobile app as themselves (e.g. an owner-operator
-- who's also on the tools), same as the original prototype's design.
create or replace function verify_staff_pin(pin text)
returns table (id uuid, full_name text, role text)
language sql security definer as $$
  select p.id, p.full_name, p.role
  from profiles p
  where p.active
    and p.pin_hash is not null
    and p.pin_hash = crypt(pin, p.pin_hash)
  limit 1;
$$;

revoke all on function verify_staff_pin(text) from public;
grant execute on function verify_staff_pin(text) to anon, authenticated;

-- =========================================================================
-- Bootstrap
-- =========================================================================

-- No default admin is seeded. After creating your first user via the
-- Supabase Dashboard (Authentication -> Users -> Add user), promote them to
-- superadmin manually:
--
--   insert into profiles (auth_user_id, full_name, role)
--   values ('<their auth.users id>', 'Your Name', 'superadmin');
